### ISSUE TITLE
Suggestion:  Version # Display

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#17]
At some point in development, it would probably be helpful if the GUI could display a "Version Number" so that end-users could easily identify if they were using the latest build.

Additionally, I would think it would be helpful when an end-user has a question or wishes to report an issue if they could easily identify the version of the app being run in their communication to you, or amongst each  other.

**Comment by jmason86** [comment]
That is an extremely good idea and I was thinking about doing the exact same thing after seeing so many screenshots but not having an indicator for which version people are running. 7f2feb6 does exactly this (plus I made a quick shell script for recompile the UI since I'll likely be updating it a lot more frequently now to keep that version number updated).
