### ISSUE TITLE
Python3 required?

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#18]
Great to see you back on the verge of having another spacecraft in orbit!

In taking a first stab at running the new decoder on Ubuntu 16.04 (64-bit), I ran the suggested command and got the following:

```
k4kdr@:~/MinXSS_Beacon_Decoder$ python minxss_beacon_decoder.py 
  File "minxss_beacon_decoder.py", line 73
    print("[input_properties]", file=config_file)
                                    ^
SyntaxError: invalid syntax
```

... however, I do NOT get this error when running the command as:

`python3 minxss_beacon_decoder.py `

... is Python3 actually what is required to run this code?  If so, it might be helpful to people if that is included in the instructions (please forgive if it is, and I just overlooked it).

-Scott,  K4KDR

**Comment by jmason86** [comment]
Good catch. Yep yep, using python 3 now. I'll update the README to state that explicitly. It'll also be in the environment.yml file that I'll upload shortly. 
I'll probably be getting rid of that ```print``` line of code since things shouldn't be printed to console but to the log file, which would make the code almost entirely agnostic to python 2 vs 3. 
But note that the Python Software Foundation will be [ending support for python 2 in 2020](https://pythonclock.org/).

**Comment by jmason86** [comment]
The [environment.yml](https://github.com/jmason86/MinXSS_Beacon_Decoder/blob/master/environment.yml) file is now in the repository. [Here's how to apply it](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) if you're using anaconda.

**Comment by jmason86** [comment]
I've also updated the README to call out python 3. Going to close this issue but feel feel free to reopen if you don't think it's resolved.
