### ISSUE TITLE
Windows:  upload filename

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#28]
After a successful test of the app (v2.0.2)  on Windows-7 (64-bit), I noticed an anomaly in the log file related to the file name used by the upload process:

![windows-logfile-filename-issue](https://user-images.githubusercontent.com/19886368/46547539-34229300-c89a-11e8-9e43-5c9a44e138ae.png)

... in the linux version, the proper file name of the current telemetry decode is used.   In Windows, it simply says, **"filename"**.

**Comment by jmason86** [comment]
Well that's _really_ weird. And I don't see any file on the server from that time either. Will have a deeper look soon.

**Comment by K4KDR** [comment]
Just a Windows FYI:  after moving all the files to

`C:\Users\{username}\MinXSS_Beacon_Decoder`

... the application continued to work properly but the "**filename**" placeholder continues to be used when the upload is triggered (as seen in the LOG file). 

A reminder that I'm on Python 3.7 if that changes anything about how **file_upload.py** parses the

`file_to_send = {'filename': (filename, open(filename, 'rb'))}`

line of code.

**Comment by jmason86** [comment]
Just an update. I am working on this issue. I see the same problem in Windows 10, and I even made sure to be using the same exact version of python and `requests` that I use on macOS. It works on macOS (and Linux for you) but for some reason `requests` has different behavior on Windows. I've [posed the question on stackoverflow](https://stackoverflow.com/questions/52796113/os-dependent-behavior-of-requests-post) and am hoping someone has a good answer else I may have to jury rig something.

**Comment by jmason86** [comment]
Fixed! That stackoverflow question resulted in the answer. The problem was that the server can't handle backslashes in the filename. Never saw this before because macOS and Linux use forward slashes but Windows uses \. Commit b91049fa824e43e5521aa98c51ecf19ec05be96c adds a couple lines of code to fileupload to force the use of forward slashes, which python is smart enough to understand on all platforms. I've tested this now on macOS and Windows 7 and Windows 10. Closing the issue!
