### ISSUE TITLE
Provide some hardware information?

### ISSUE THREAD

**Issue by inktomi** [jmason86/MinXSS_Beacon_Decoder#7]
It would be great to have a basic build out listed for hardware needed to use this. I'd love to build it and use my HAM license to watch the spacecraft, but I'm unsure of getting the proper radios and such for this. A couple paragraphs or links in the README would be awesome!

**Comment by K4KDR** [comment]
I can't speak for the author, but wanted to provide a couple of links to help answer your questions.  You asked specifically about hardware, but any antenna/radio or antenna/SDR combination capable of receiving the desired frequency can normally be used to receive satellite telemetry.  But as you probably know, receiving the radio signal is only a small part of the equation.

It's difficult to be very helpful without knowing how comfortable you are with receiving & decoding satellite telemetry in general, but no matter your level of experience, here are a couple of great resources.

A great general how-to on what is involved with receiving satellite telemetry can be found at:  http://www.pe0sat.vgnet.nl/decoding/block-diagram/

... please note that it always takes the interaction between multiple software apps to turn an RF signal into human-readable values on a screen.

If you would like to focus on using the linux operating system for doing this sort of thing, here is an overview of what is involved on that platform:  http://www.pe0sat.vgnet.nl/decoding/unix-tlm-decoding/

I suppose that the most significant point that I can make is that there is much more required on the computer side of things than on the radio hardware side when working with satellite telemetry.  Hope that helps!

**Comment by inktomi** [comment]
I've built SDR systems for hobby high altitude balloon tracking using APRS and this seems like it'd be a fun project to sort of move up a level. That's why I was asking - thank you for the info!

**Comment by jmason86** [comment]
The resources provided above are better than what I could provide. Every setup is a little different and I'd recommend googling around for advice. All I can speak to is the couple of setups we've done. I'm not sure if I want to include that in the README however because I don't want people to think they need the same hardware setup as us to get it to work. I already provided the frequency and the beacon rates to expect. I've now also added the modulation scheme. Any system capable of receiving with those parameters will be able to use the beacon decoder. 

As K4KDR mentioned, there's multiple software tools that will be required, many of which are free. We use SatPC32 and GPredict for satellite tracking and automatic Doppler shifting. If you use an SDR, then you should be able to connect this decoder to it via TCP/IP. If you use a hardware radio and a TNC, then you should be able to connect the decoder to that with the serial interface. Development on that is a little bit lagged at the moment so there's likely some bugs. 

You should do it! Definitely a fun and brag-worthy hobby. 

I'm closing this issue but am willing to compile and post our specific hardware setup if demand mounts.
